### ISSUE TITLE
Date picker button broken in create class

### ISSUE THREAD

**Issue by neloe** [HarshithaChettyRagava/GDP1_Team1#14]
When I go to create a class the date picker button does not bring up any date selector. This appears to be because jquery is not loaded (https is needed):
![image](https://user-images.githubusercontent.com/278757/68310536-cedd3a80-0075-11ea-95dd-921519dc4216.png)

I believe that by loading jquery from https (or downloading and hosting your own) will fix that problem.  I don't know if this is chrome specific or is a problem on other browsers.

Easy fix (change http to https, or download and host own version of jquery).  This may need to be fixed throughout the webapp.

**Comment by HarshithaChettyRagava** [comment]
We have fixed this issue by changing Http to https in jquery URL and have been pushed to Heroku.
