### ISSUE TITLE
Editing class shows JS errors

### ISSUE THREAD

**Issue by neloe** [HarshithaChettyRagava/GDP1_Team1#16]
Going to edit a class gives some errors involving fileupload.js

![image](https://user-images.githubusercontent.com/278757/68311531-48295d00-0077-11ea-9a53-d3323ef61686.png)

Might be fixed when jquery is imported correctly? Possibly related: #14 

Priority: LOW (maybe, it depends on what functionality is missing if any)

**Comment by HarshithaChettyRagava** [comment]
Fixed by importing jquery correctly with the inclusion of https instead of HTTP
