### ISSUE TITLE
Number of students incorrect

### ISSUE THREAD

**Issue by neloe** [HarshithaChettyRagava/GDP1_Team1#17]
After creating a course and uploading a text file with two email addresses, I see the following:

![image](https://user-images.githubusercontent.com/278757/68311712-8f175280-0077-11ea-945c-b27f1968799f.png)

It says there are 50 words to acknowledge, but there should be only two students in the class (should report 0/2

May have something to do with how you store student lists (or I uploaded them incorrectly, that is 100% a possiblity).

**Comment by HarshithaChettyRagava** [comment]
Resolved the issue by dynamically fetching number of students from the DB
